FROM ubuntu:20.04


# Install wget
RUN apt-get update && apt-get install -y wget  

# Download SRA toolkit and add to path
RUN wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.8/sratoolkit.2.10.8-ubuntu64.tar.gz \
	&& tar xvzf sratoolkit.2.10.8-ubuntu64.tar.gz
ENV PATH="/sratoolkit.2.10.8-ubuntu64/bin:${PATH}"

# Configure environment
COPY ncbi_config /root/.ncbi/user-settings.mkfg
#RUN echo "Aexyo" | sratoolkit.2.10.8-ubuntu64/bin/vdb-config -i
